sudo: required
dist: bionic
language: cpp
compiler:
  - gcc
#  - clang


before_install:
  - sudo apt-get update
  - sudo apt-get install -y qt5-default libqwt-qt5-dev libfftw3-dev libglu1-mesa-dev libasound2-dev libqt5opengl5-dev

script:
  - qmake pitch.pro
  - make
  - mkdir cmake-build; cd cmake-build
  - cmake ..
  - make
#EOF
